// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wiki;

namespace wiki.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    [Migration("20190708183531_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("wiki.Models.Page", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("snippet");

                    b.Property<long>("timestamp");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.ToTable("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
